[package]
name = "toddlike"
version = "0.1.0"
authors = ["Todd Hainsworth <hainsworth.todd@gmail.com>"]
edition = "2018"

[dependencies]
specs = "0.16.1"
specs-derive = "0.4.1"

[dependencies.bracket-lib]
version = "0.8.1"
default-features = true
features = ["specs", "serde"]
